# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=1024)),
                ('days', models.IntegerField(default=-1)),
                ('publish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
