# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaction',
            name='name',
            field=models.CharField(db_index=True, default='New URL Action', max_length=1024),
        ),
        migrations.AlterField(
            model_name='urlaction',
            name='url',
            field=models.URLField(db_index=True, max_length=1024),
        ),
    ]
