# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0002_auto_20160327_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaction',
            name='identifier',
            field=models.CharField(db_index=True, default='survey', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
