# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0003_urlaction_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=1024)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
