# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0004_providedidentifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('category', models.CharField(default='Other', max_length=1024)),
                ('match_type', models.CharField(choices=[('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match'), ('domainExact', 'Exact Domain Match')], max_length=1024)),
                ('match_value', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
