# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0005_urlcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcategory',
            name='match_type',
            field=models.CharField(choices=[('domainExact', 'Exact Domain Match'), ('topDomainExact', 'Root Domain Match')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='urlcategory',
            name='match_value',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
